version: '2'

services:
  web:
    env_file:
      - .env
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "${PORT}:${PORT}"
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - /data/db