version: '2'

services:
  app:
    build: .
    env_file:
      - ./config/vars/prod.env
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    command: npm run production

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - /data/db