version: '2'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    env_file:
      - ./config/vars/prod.env
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    command: npm run production
  test:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    env_file:
      - ./config/vars/test.env
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
    command: npm run test
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - /data/db